# Generated by Django 5.0.6 on 2024-09-01 14:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('tuition_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfantPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infant_dni', models.CharField(max_length=8, verbose_name='Infant DNI')),
                ('infant_name', models.CharField(max_length=100, verbose_name="Infant's Full Name")),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('guardian_dni', models.CharField(max_length=8, verbose_name='Guardian DNI')),
                ('guardian_name', models.CharField(max_length=100, verbose_name="Guardian's Full Name")),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name="Guardian's Email")),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Contact Phone')),
                ('district', models.CharField(max_length=255, verbose_name='Address')),
                ('psychology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='autdetect.psychologists')),
            ],
            options={
                'verbose_name': 'Infant Patient',
                'verbose_name_plural': 'Infant Patients',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(verbose_name='Question 1')),
                ('question_2', models.BooleanField(verbose_name='Question 2')),
                ('result', models.BooleanField(verbose_name='Autism Diagnosis')),
                ('probability', models.FloatField(verbose_name='Autism Probability')),
                ('date_evaluation', models.DateField(blank=True, verbose_name='Date of Evaluation')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autdetect.infantpatient', verbose_name='Infant Patient')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 54, 45, 114083, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
