# Generated by Django 5.0.6 on 2024-09-04 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autdetect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologists',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 0, 39, 37, 203112, tzinfo=datetime.timezone.utc)),
        ),
    ]
