# Generated by Django 5.0.6 on 2024-09-19 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autdetect', '0003_userprofile_code_change_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_2',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='familiar_con_tea',
            field=models.IntegerField(default=0, verbose_name='Familiar con TEA'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='ictericia',
            field=models.IntegerField(default=0, verbose_name='Ictericia'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_1',
            field=models.IntegerField(default=0, verbose_name='Pregunta 1'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_10',
            field=models.IntegerField(default=0, verbose_name='Cociente Espectro Autista'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_2',
            field=models.IntegerField(default=0, verbose_name='Pregunta 2'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_3',
            field=models.IntegerField(default=0, verbose_name='Pregunta 3'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_4',
            field=models.IntegerField(default=0, verbose_name='Pregunta 4'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_5',
            field=models.IntegerField(default=0, verbose_name='Pregunta 5'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_6',
            field=models.IntegerField(default=0, verbose_name='Pregunta 6'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_7',
            field=models.IntegerField(default=0, verbose_name='Pregunta 7'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_8',
            field=models.IntegerField(default=0, verbose_name='Pregunta 8'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pregunta_9',
            field=models.IntegerField(default=0, verbose_name='Pregunta 9'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sexo',
            field=models.IntegerField(default=0, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date_evaluation',
            field=models.DateField(blank=True, default=0, verbose_name='Date of Evaluation'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='probability',
            field=models.FloatField(default=0, verbose_name='Autism Probability'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='result',
            field=models.BooleanField(default=0, verbose_name='Autism Diagnosis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 22, 40, 27, 524689, tzinfo=datetime.timezone.utc)),
        ),
    ]
