# Generated by Django 5.0.6 on 2024-09-21 01:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autdetect', '0005_remove_questionnaire_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autdetect.infantpatient', verbose_name='Infant Patient'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 1, 27, 24, 539998, tzinfo=datetime.timezone.utc)),
        ),
    ]
