# Generated by Django 5.0.6 on 2024-09-23 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autdetect', '0006_alter_questionnaire_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infantpatient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 4, 34, 29, 815051, tzinfo=datetime.timezone.utc)),
        ),
    ]
